<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EDIOI3Q" failures="1" tests="6" name="SeleniumFramework.Test.ErrorValidationTest" time="48.013" errors="0" timestamp="2025-03-18T18:08:35 IST" skipped="4">
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="5.597">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="5.479">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="5.414">
    <failure message="expected:&lt;Incorrect email password.&gt; but was:&lt;Incorrect email or password.&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<Incorrect email password.> but was:<Incorrect email or password.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at SeleniumFramework.Test.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="5.724">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="14.386">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="productErrorValidation" time="11.413"/>
</testsuite> <!-- SeleniumFramework.Test.ErrorValidationTest -->
